name: Deploy Docker Compose to EC2

on:
  push:
    branches:
      - main # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: DEV # Specify the environment here
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload Docker Compose file
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ vars.EC2_USER }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        # Ensure the SSH key is available
        mkdir -p ~/.ssh
        echo "$EC2_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # Upload the Docker Compose file to the EC2 instance
        pwd
        ls -lhtra
        scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa unity/compose.yaml $EC2_USER@$EC2_HOST:/home/$EC2_USER/compose.yaml

    - name: SSH and deploy
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ vars.EC2_USER }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |  
        # Deploy using SSH
        echo "Connecting to EC2 instance as user $EC2_USER at $EC2_HOST"
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $EC2_USER@$EC2_HOST << 'SH'
          echo "==================== $EC2_USER ============= "
          cd /home/$EC2_USER
          pwd
          hostname -I
          ls -lhtra

          # Start or update the Docker Compose application
          ocker-compose -f compose.yaml up -d
        SH
